### ISSUE TITLE
Embedding records data

### ISSUE THREAD

**Issue by blha303** [speedruncomorg/api#42]
It would be extremely handy to be able to embed data like records that's accessible from a resource. By that I mean, if you can access /games/\<id\>/records, being able to embed records data would save an API request and the time associated with it. It would also simplify the problem I'm having with https://github.com/blha303/srcomapi where requesting the records data as a class attribute is causing some issues; if the data was in the request to start with there would be no issues.

Overall the embed feature could be expanded to support more data types, although I'm unaware of the impact this would have on the database, obviously it's up to the owners of speedrun.com but doing a join in a database query is faster than making multiple API requests and joining them on the other end.

**Comment by Lighnat0r** [comment]
Improving how using /records works is on my to-do list.
Could you provide specific example request(s) that you'd want to work but doesn't (or doesn't work the way you want) since I'm not completely sure what you're after, and I'd rather not go digging through your code to find out where you're having issues.

**Comment by blha303** [comment]
Without using embeds, it takes three requests to get the current world record for a category in a game. I'm retrieving information for the GDQ vod thread so I have to look up the correct category and then retrieve records for it. [A request to /games](https://www.speedrun.com/api/v1/games?name=Super%20Mario%20Sunshine) to get the url for category information, [a request to /games/id/categories](https://www.speedrun.com/api/v1/games/v1pxjz68/categories) for the list of categories, and then [a request to /categories/id/records](https://www.speedrun.com/api/v1/categories/n2y3r8do/records) to get the world record.

Ideally, I would be able to embed records information in the category results with ?embed=categories.records, maybe also in the game results but then there's the issue of it not being specific to the desired category. Then again, most of the time I'd imagine users are likely to want the any% record.

**Comment by Judas** [comment]
:+1: on this. I'm making an Android app from this API and I would gladly have to get the records directly embedded in a single **/runs?embed=category.records,level.records** request.
Right now it takes 2 requests for that (request the runs with their level/categories then request the level/category for its records).
